apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mongodb-pv
spec: 
  accessModes: 
  - ReadWriteOnce
  - ReadOnlyMany
  capacity: 
    storage: 1Gi 
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk: 
    pdName: mongodb
    fsType: ext4
